CREATE TABLE ES_usuario (
  id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_usuario      VARCHAR2(120) NOT NULL,
  nm_email        VARCHAR2(180) NOT NULL UNIQUE,
  tp_papel        VARCHAR2(20)  NOT NULL,
  dt_criacao      TIMESTAMP     NOT NULL,
  CONSTRAINT ck_usuario_papel CHECK (tp_papel IN ('ESTUDANTE','ONG','EMPRESA','UNIVERSIDADE','ADMIN'))
);

CREATE TABLE ES_organizacao (
  id_organizacao  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_organizacao  VARCHAR2(160) NOT NULL,
  tp_organizacao  VARCHAR2(20)  NOT NULL,
  nm_email_contato VARCHAR2(180) NOT NULL,
  st_verificada   CHAR(1)       DEFAULT 'N' CHECK (st_verificada IN ('S','N')),
  dt_criacao      TIMESTAMP     NOT NULL,
  CONSTRAINT ck_organizacao_tipo CHECK (tp_organizacao IN ('ONG','UNIVERSIDADE','EMPRESA','PREFEITURA'))
);

CREATE TABLE ES_projeto (
  id_projeto      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_organizacao  NUMBER NOT NULL,
  id_responsavel  NUMBER NOT NULL,
  nm_titulo       VARCHAR2(140) NOT NULL,
  ds_projeto      CLOB NOT NULL,
  st_projeto      VARCHAR2(20) NOT NULL,
  dt_criacao      TIMESTAMP NOT NULL,
  CONSTRAINT fk_proj_org FOREIGN KEY (id_organizacao) REFERENCES ES_organizacao(id_organizacao),
  CONSTRAINT fk_proj_resp FOREIGN KEY (id_responsavel) REFERENCES ES_usuario(id_usuario),
  CONSTRAINT ck_projeto_status CHECK (st_projeto IN ('RASCUNHO','ATIVO','EM_ANDAMENTO','CONCLUIDO','ARQUIVADO'))
);

CREATE TABLE ES_candidatura (
  id_candidatura  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario      NUMBER NOT NULL,
  id_projeto      NUMBER NOT NULL,
  st_candidatura  VARCHAR2(20) NOT NULL,
  vl_horas_previstas NUMBER(6,1) NOT NULL,
  vl_horas_entregues NUMBER(6,1) DEFAULT 0 NOT NULL,
  dt_candidatura  TIMESTAMP NOT NULL,
  CONSTRAINT fk_cand_user FOREIGN KEY (id_usuario) REFERENCES ES_usuario(id_usuario),
  CONSTRAINT fk_cand_proj FOREIGN KEY (id_projeto) REFERENCES ES_projeto(id_projeto),
  CONSTRAINT uk_candidatura UNIQUE (id_usuario, id_projeto),
  CONSTRAINT ck_cand_status CHECK (st_candidatura IN ('PENDENTE','ACEITA','RECUSADA','CANCELADA','CONCLUIDA')),
  CONSTRAINT ck_horas_nonneg CHECK (vl_horas_previstas >= 0 AND vl_horas_entregues >= 0)
);

CREATE TABLE ES_evidencia (
  id_evidencia    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_projeto      NUMBER NOT NULL,
  id_autor        NUMBER NOT NULL,
  tp_evidencia    VARCHAR2(20) NOT NULL,
  nm_caminho_arquivo VARCHAR2(300) NOT NULL,
  nm_indicador_impacto VARCHAR2(80) NOT NULL,
  vl_indicador    NUMBER(12,2) NOT NULL,
  dt_envio        TIMESTAMP NOT NULL,
  CONSTRAINT fk_evid_proj FOREIGN KEY (id_projeto) REFERENCES ES_projeto(id_projeto),
  CONSTRAINT fk_evid_autor FOREIGN KEY (id_autor) REFERENCES ES_usuario(id_usuario),
  CONSTRAINT ck_evid_tipo CHECK (tp_evidencia IN ('DOCUMENTO','IMAGEM','RELATORIO','LINK'))
);

CREATE TABLE ES_relatorio_impacto (
  id_relatorio    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_projeto      NUMBER NOT NULL,
  cd_ods_meta     VARCHAR2(10) NOT NULL,
  nm_indicador    VARCHAR2(120) NOT NULL,
  vl_indicador    NUMBER(12,2) NOT NULL,
  dt_relatorio    DATE NOT NULL,
  CONSTRAINT fk_rel_proj FOREIGN KEY (id_projeto) REFERENCES ES_projeto(id_projeto),
  CONSTRAINT uk_relatorio UNIQUE (id_projeto, cd_ods_meta, nm_indicador, dt_relatorio),
  CONSTRAINT ck_rel_ods_meta CHECK (cd_ods_meta IN ('ODS1','ODS2','ODS3','ODS4','ODS5','ODS6','ODS7','ODS8','ODS9','ODS10','ODS11','ODS12','ODS13','ODS14','ODS15','ODS16','ODS17'))
);

CREATE TABLE ES_habilidade (
  id_habilidade   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_habilidade   VARCHAR2(80) NOT NULL UNIQUE,
  tp_categoria    VARCHAR2(40) NOT NULL,
  ds_habilidade   VARCHAR2(200)
);

CREATE TABLE ES_usuario_habilidade (
  id_usuario_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario      NUMBER NOT NULL,
  id_habilidade   NUMBER NOT NULL,
  st_nivel        VARCHAR2(20) NOT NULL,
  vl_anos_experiencia NUMBER(4,1) NOT NULL,
  CONSTRAINT fk_uh_user FOREIGN KEY (id_usuario) REFERENCES ES_usuario(id_usuario),
  CONSTRAINT fk_uh_hab FOREIGN KEY (id_habilidade) REFERENCES ES_habilidade(id_habilidade),
  CONSTRAINT uk_usuario_habilidade UNIQUE (id_usuario, id_habilidade),
  CONSTRAINT ck_nivel CHECK (st_nivel IN ('BASICO','INTERMEDIARIO','AVANCADO')),
  CONSTRAINT ck_anos_nonneg CHECK (vl_anos_experiencia >= 0)
);

CREATE TABLE ES_projeto_ods (
  id_projeto_ods  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_projeto      NUMBER NOT NULL,
  cd_ods_meta     VARCHAR2(10) NOT NULL,
  CONSTRAINT fk_proj_ods FOREIGN KEY (id_projeto) REFERENCES ES_projeto(id_projeto),
  CONSTRAINT uk_projeto_ods UNIQUE (id_projeto, cd_ods_meta),
  CONSTRAINT ck_proj_ods_meta CHECK (cd_ods_meta IN ('ODS1','ODS2','ODS3','ODS4','ODS5','ODS6','ODS7','ODS8','ODS9','ODS10','ODS11','ODS12','ODS13','ODS14','ODS15','ODS16','ODS17'))
);